import type { ChessLesson } from "./types";

export const DEFENSE_LESSONS: ChessLesson[] = [
  {
    id: "sicilian-defense",
    name: "Defensa Siciliana",
    eco: "B20",
    category: "defense",
    studentColor: "b",
    description: "La defensa más popular contra 1.e4.",
    keyIdeas: ["Asimetría", "Contraataque en el flanco de dama", "Lucha por d5"],
    steps: [
      { move: "e4", explanation: "Blancas ocupan el centro." },
      { move: "c5", explanation: "La Siciliana: control lateral y juego asimétrico." },
      { move: "Nf3", explanation: "Desarrollo y presión sobre d4." },
      { move: "d6", explanation: "Prepara Nf6 y un centro flexible." },
      { move: "d4", explanation: "Blancas abren el centro." },
      { move: "cxd4", explanation: "Capturas y abres la columna c." },
      { move: "Nxd4", explanation: "Blancas recapturan." },
      { move: "Nf6", explanation: "Desarrollo natural atacando e4." },
      { move: "Nc3", explanation: "Defiende e4 y desarrolla." },
      { move: "a6", explanation: "La Najdorf: controla b5 y prepara expansión." },
      { move: "Be3", explanation: "Desarrollo activo de blancas." },
      { move: "e5", explanation: "Ganas espacio y alejas el caballo d4." },
    ],
  },
  {
    id: "sicilian-dragon",
    name: "Siciliana - Dragón",
    eco: "B70",
    category: "defense",
    studentColor: "b",
    description: "Fianchetto agresivo del alfil de rey.",
    keyIdeas: ["g6 y Bg7", "Ataque contrario en flancos", "Columna h abierta"],
    steps: [
      { move: "e4", explanation: "Centro blanco." },
      { move: "c5", explanation: "Siciliana." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "d6", explanation: "Base sólida." },
      { move: "d4", explanation: "Apertura central." },
      { move: "cxd4", explanation: "Captura." },
      { move: "Nxd4", explanation: "Recaptura." },
      { move: "Nf6", explanation: "Desarrollo." },
      { move: "Nc3", explanation: "Desarrollo blanco." },
      { move: "g6", explanation: "El Dragón: prepara fianchetto." },
      { move: "Be3", explanation: "Desarrollo activo." },
      { move: "Bg7", explanation: "Alfil en la gran diagonal, muy poderoso." },
    ],
  },
  {
    id: "sicilian-alapin",
    name: "Siciliana - Alapin",
    eco: "B22",
    category: "defense",
    studentColor: "b",
    description: "Respuesta sólida contra el sistema Alapin (c3).",
    keyIdeas: ["d5 central", "Desarrollo rápido", "Evitar complicaciones"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "c5", explanation: "Siciliana." },
      { move: "c3", explanation: "El Alapin de blancas." },
      { move: "d5", explanation: "Golpe central inmediato: la mejor respuesta." },
      { move: "exd5", explanation: "Blancas capturan." },
      { move: "Qxd5", explanation: "La dama recupera con un puesto activo." },
      { move: "d4", explanation: "Blancas buscan centro." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "e6", explanation: "Sólido y prepara desarrollo." },
      { move: "Be2", explanation: "Desarrollo tranquilo." },
      { move: "Nc6", explanation: "Desarrollo y presión sobre d4." },
    ],
  },
  {
    id: "french-defense",
    name: "Defensa Francesa",
    eco: "C00",
    category: "defense",
    studentColor: "b",
    description: "Sólida contra 1.e4 con estructura de peones firme.",
    keyIdeas: ["e6 y d5", "Cadena de peones", "Contraataque en el flanco de dama"],
    steps: [
      { move: "e4", explanation: "Centro blanco." },
      { move: "e6", explanation: "La Francesa: prepara d5 sin liberar la dama." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "d5", explanation: "Golpe central: desafías el centro blanco." },
      { move: "Nc3", explanation: "Desarrollo y defensa de e4." },
      { move: "Nf6", explanation: "Desarrollo natural presionando e4." },
      { move: "Bg5", explanation: "Clavada molesta." },
      { move: "Be7", explanation: "Rompe la clavada y prepara el enroque." },
      { move: "e5", explanation: "Ganas espacio en el flanco de rey." },
      { move: "Nfd7", explanation: "El caballo retrocede pero consolida." },
      { move: "Nf3", explanation: "Desarrollo blanco." },
      { move: "O-O", explanation: "Seguridad del rey." },
    ],
  },
  {
    id: "caro-kann",
    name: "Defensa Caro-Kann",
    eco: "B10",
    category: "defense",
    studentColor: "b",
    description: "Sólida y difícil de romper.",
    keyIdeas: ["c6 y d5", "Estructura sólida", "Juego posicional"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "c6", explanation: "Caro-Kann: prepara d5 con apoyo." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "d5", explanation: "Golpe central inmediato." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "dxe4", explanation: "Capturas para simplificar el centro." },
      { move: "Nxe4", explanation: "Recaptura activa." },
      { move: "Bf5", explanation: "Desarrolla el alfil antes de e6." },
      { move: "Ng3", explanation: "Ataca el alfil." },
      { move: "Bg6", explanation: "Mantiene el alfil activo." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nd7", explanation: "Desarrollo sólido y flexible." },
    ],
  },
  {
    id: "scandinavian",
    name: "Defensa Escandinava",
    eco: "B01",
    category: "defense",
    studentColor: "b",
    description: "Respuesta directa con 1...d5.",
    keyIdeas: ["d5 inmediato", "Desarrollo rápido", "Juego abierto"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "d5", explanation: "La Escandinava: desafío central directo." },
      { move: "exd5", explanation: "Blancas capturan." },
      { move: "Qxd5", explanation: "Recuperas con la dama activa." },
      { move: "Nc3", explanation: "Ataca la dama ganando tiempo." },
      { move: "Qa5", explanation: "La dama mantiene presión sobre e4." },
      { move: "d4", explanation: "Centro sólido." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Bg4", explanation: "Clavada sobre el caballo f3." },
      { move: "Be2", explanation: "Desarrollo tranquilo." },
      { move: "Nc6", explanation: "Desarrollo y presión sobre d4." },
    ],
  },
  {
    id: "pirc-defense",
    name: "Defensa Pirc",
    eco: "B07",
    category: "defense",
    studentColor: "b",
    description: "Hipermoderna: deja el centro a blancas.",
    keyIdeas: ["g6 y Bg7", "Contraataque central", "Fianchetto"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "d6", explanation: "La Pirc: prepara fianchetto." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "Nf6", explanation: "Desarrollo y presión sobre e4." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "g6", explanation: "Prepara el fianchetto." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Bg7", explanation: "Alfil en la diagonal larga." },
      { move: "Be2", explanation: "Desarrollo sólido." },
      { move: "O-O", explanation: "Enroque para seguridad." },
      { move: "O-O", explanation: "Enroque blanco." },
      { move: "c6", explanation: "Prepara d5 o e5." },
    ],
  },
  {
    id: "alekhine-defense",
    name: "Defensa Alekhine",
    eco: "B02",
    category: "defense",
    studentColor: "b",
    description: "Provoca el avance de peones blancos para contraatacar.",
    keyIdeas: ["Nf6 provocando", "Centro amplio blanco", "Contraataque"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "Nf6", explanation: "La Alekhine: provoca el avance de peones." },
      { move: "e5", explanation: "Blancas avanzan atacando el caballo." },
      { move: "Nd5", explanation: "El caballo se centraliza." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "d6", explanation: "Atacas la base del peón e5." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "g6", explanation: "Prepara fianchetto." },
      { move: "c4", explanation: "Ataca el caballo." },
      { move: "Nb6", explanation: "El caballo retrocede a un puesto seguro." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "Bg7", explanation: "Alfil fianchettado." },
    ],
  },
  {
    id: "kings-indian",
    name: "Defensa India de Rey",
    eco: "E60",
    category: "defense",
    studentColor: "b",
    description: "Contraataque dinámico en el flanco de rey.",
    keyIdeas: ["g6 y Bg7", "f5 contrajuego", "Ataque en el flanco de rey"],
    steps: [
      { move: "d4", explanation: "Centro de dama." },
      { move: "Nf6", explanation: "Desarrollo flexible." },
      { move: "c4", explanation: "Control amplio." },
      { move: "g6", explanation: "La India de Rey: fianchetto." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "Bg7", explanation: "Alfil en la gran diagonal." },
      { move: "e4", explanation: "Centro amplio blanco." },
      { move: "d6", explanation: "Base sólida para el contraataque." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "O-O", explanation: "Enroque y prepara f5." },
      { move: "Be2", explanation: "Desarrollo tranquilo." },
      { move: "e5", explanation: "Golpe central: lucha por el centro." },
    ],
  },
  {
    id: "nimzo-indian",
    name: "Defensa Nimzo-India",
    eco: "E20",
    category: "defense",
    studentColor: "b",
    description: "Control del centro con el alfil y el caballo.",
    keyIdeas: ["Bb4 clavando", "Control de e4", "Juego posicional"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "Nf6", explanation: "Desarrollo." },
      { move: "c4", explanation: "Control amplio." },
      { move: "e6", explanation: "Prepara Bb4 y d5." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "Bb4", explanation: "La Nimzo: clavada sobre el caballo." },
      { move: "Qc2", explanation: "Defiende el caballo y mantiene el alfil." },
      { move: "O-O", explanation: "Enroque y seguridad." },
      { move: "a3", explanation: "Pregunta al alfil." },
      { move: "Bxc3+", explanation: "Intercambio que da el par de alfiles." },
      { move: "Qxc3", explanation: "Recaptura con la dama." },
      { move: "b6", explanation: "Prepara Bb7 y un fianchetto." },
    ],
  },
  {
    id: "queens-gambit-declined",
    name: "Gambito de Dama Declinado",
    eco: "D30",
    category: "defense",
    studentColor: "b",
    description: "Defensa sólida contra el gambito de dama.",
    keyIdeas: ["e6 sólido", "Desarrollo armónico", "Juego posicional"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "d5", explanation: "Control central." },
      { move: "c4", explanation: "Gambito de dama." },
      { move: "e6", explanation: "Declinado: sólido sin capturar en c4." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Bg5", explanation: "Clavada." },
      { move: "Be7", explanation: "Rompe la clavada." },
      { move: "e3", explanation: "Centro sólido." },
      { move: "O-O", explanation: "Enroque." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nbd7", explanation: "Desarrollo flexible." },
    ],
  },
  {
    id: "slav-defense",
    name: "Defensa Eslava",
    eco: "D10",
    category: "defense",
    studentColor: "b",
    description: "Sólida contra el gambito de dama con ...c6.",
    keyIdeas: ["c6 apoyando d5", "Estructura sólida", "Alfil de dama activo"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "d5", explanation: "Control central." },
      { move: "c4", explanation: "Gambito." },
      { move: "c6", explanation: "La Eslava: apoya d5 sin bloquear el alfil." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "Bf5", explanation: "Alfil activo antes de e6." },
      { move: "cxd5", explanation: "Intercambio central." },
      { move: "cxd5", explanation: "Recaptura con la columna c abierta." },
      { move: "Qb3", explanation: "Ataca b7 y el alfil." },
      { move: "Qc7", explanation: "Defiende y conecta las torres." },
    ],
  },
  {
    id: "grunfeld-defense",
    name: "Defensa Grünfeld",
    eco: "D70",
    category: "defense",
    studentColor: "b",
    description: "Hipermoderna contra el centro blanco.",
    keyIdeas: ["d5 y ...dxc4", "Contraataque central", "Fianchetto"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "Nf6", explanation: "Desarrollo." },
      { move: "c4", explanation: "Control amplio." },
      { move: "g6", explanation: "Prepara fianchetto." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "d5", explanation: "Golpe central inmediato." },
      { move: "cxd5", explanation: "Intercambio." },
      { move: "Nxd5", explanation: "Recaptura activa." },
      { move: "e4", explanation: "Centro amplio." },
      { move: "Nxc3", explanation: "Intercambio que debilita el peón d4." },
      { move: "bxc3", explanation: "Recaptura con estructura de peones doblada." },
      { move: "Bg7", explanation: "Alfil en la diagonal larga presionando." },
    ],
  },
  {
    id: "dutch-defense",
    name: "Defensa Holandesa",
    eco: "A80",
    category: "defense",
    studentColor: "b",
    description: "Agresiva con el peón f avanzado.",
    keyIdeas: ["f5 activo", "Ataque en flanco de rey", "Juego asimétrico"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "f5", explanation: "La Holandesa: agresiva desde el inicio." },
      { move: "c4", explanation: "Control amplio." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "e6", explanation: "Sólido y prepara Fianchetto." },
      { move: "g3", explanation: "Fianchetto blanco." },
      { move: "Be7", explanation: "Desarrollo sólido." },
      { move: "Bg2", explanation: "Alfil en la diagonal." },
      { move: "O-O", explanation: "Enroque." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "d6", explanation: "Consolida el centro y prepara e5." },
    ],
  },
  {
    id: "petroff-defense",
    name: "Defensa Petroff",
    eco: "C42",
    category: "defense",
    studentColor: "b",
    description: "Sólida e igualadora contra 1.e4.",
    keyIdeas: ["Simetría", "Juego sólido", "Evitar tácticas tempranas"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "e5", explanation: "Simetría central." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nf6", explanation: "La Petroff: ataca e4 directamente." },
      { move: "Nxe5", explanation: "Captura del peón." },
      { move: "d6", explanation: "Atacas el caballo y desarrollas." },
      { move: "Nf3", explanation: "El caballo retrocede." },
      { move: "Nxe4", explanation: "Recuperas el peón." },
      { move: "d4", explanation: "Centro sólido." },
      { move: "d5", explanation: "Golpe central fuerte." },
      { move: "Bd3", explanation: "Ataca el caballo." },
      { move: "Bd6", explanation: "Desarrollo activo del alfil." },
    ],
  },
  {
    id: "philidor-defense",
    name: "Defensa Philidor",
    eco: "C41",
    category: "defense",
    studentColor: "b",
    description: "Sólida pero pasiva, ideal para aprender estructuras.",
    keyIdeas: ["d6 sólido", "Desarrollo armónico", "Evitar debilidades"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "e5", explanation: "Simetría." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "d6", explanation: "La Philidor: sólida pero pasiva." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "Nd7", explanation: "Desarrollo flexible." },
      { move: "Bc4", explanation: "Alfil activo." },
      { move: "Be7", explanation: "Desarrollo natural." },
      { move: "O-O", explanation: "Enroque blanco." },
      { move: "Ngf6", explanation: "Completa el desarrollo de caballos." },
      { move: "Re1", explanation: "Torre centralizada." },
      { move: "O-O", explanation: "Enroque negro." },
    ],
  },
  {
    id: "modern-defense",
    name: "Defensa Moderna",
    eco: "B06",
    category: "defense",
    studentColor: "b",
    description: "Flexible con g6 contra cualquier primera jugada.",
    keyIdeas: ["g6 universal", "Fianchetto", "Contraataque tardío"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "g6", explanation: "La Moderna: flexible contra cualquier sistema." },
      { move: "d4", explanation: "Centro amplio." },
      { move: "Bg7", explanation: "Alfil fianchettado." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "d6", explanation: "Base sólida." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Be2", explanation: "Desarrollo tranquilo." },
      { move: "O-O", explanation: "Enroque." },
      { move: "O-O", explanation: "Enroque blanco." },
      { move: "c6", explanation: "Prepara d5." },
    ],
  },
  {
    id: "benoni-defense",
    name: "Defensa Benoni",
    eco: "A56",
    category: "defense",
    studentColor: "b",
    description: "Asimétrica y dinámica contra 1.d4.",
    keyIdeas: ["c5 contrajuego", "Columnas abiertas", "Juego dinámico"],
    steps: [
      { move: "d4", explanation: "Centro." },
      { move: "Nf6", explanation: "Desarrollo." },
      { move: "c4", explanation: "Control amplio." },
      { move: "c5", explanation: "La Benoni: contrajuego inmediato." },
      { move: "d5", explanation: "Centro avanzado." },
      { move: "e6", explanation: "Atacas la base del peón d5." },
      { move: "Nc3", explanation: "Desarrollo." },
      { move: "exd5", explanation: "Abres el centro." },
      { move: "cxd5", explanation: "Recaptura." },
      { move: "d6", explanation: "Centro sólido y bloquea el peón." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "g6", explanation: "Prepara fianchetto." },
    ],
  },
];