import type { ChessLesson } from "./types";

export const OPENING_LESSONS: ChessLesson[] = [
  {
    id: "italian-game",
    name: "Gambito Italiano",
    eco: "C50",
    category: "opening",
    studentColor: "w",
    description: "Desarrollo rápido y presión sobre f7.",
    keyIdeas: ["Control del centro", "Desarrollar piezas menores", "Atacar f7"],
    steps: [
      { move: "e4", explanation: "Ocupa el centro y libera la dama y el alfil." },
      { move: "e5", explanation: "Negro contesta en el centro simétricamente." },
      { move: "Nf3", explanation: "Desarrolla el caballo atacando el peón e5." },
      { move: "Nc6", explanation: "Defiende e5 y desarrolla el caballo." },
      { move: "Bc4", explanation: "El alfil apunta a f7, el punto más débil de negro." },
      { move: "Bc5", explanation: "Negro desarrolla su alfil de forma activa." },
      { move: "c3", explanation: "Prepara d4 para ganar espacio en el centro." },
      { move: "Nf6", explanation: "Desarrollo natural del caballo con presión sobre e4." },
      { move: "d4", explanation: "Golpe central: desafía la estructura de negro." },
      { move: "exd4", explanation: "Negro captura en d4." },
      { move: "cxd4", explanation: "Recuperas el peón con un centro sólido." },
      { move: "Bb4+", explanation: "Jaque útil que fuerza una respuesta." },
    ],
  },
  {
    id: "ruy-lopez",
    name: "Ruy López",
    eco: "C60",
    category: "opening",
    studentColor: "w",
    description: "La apertura clásica por excelencia.",
    keyIdeas: ["Presión sobre el caballo c6", "Control del centro", "Juego posicional"],
    steps: [
      { move: "e4", explanation: "Control central inmediato." },
      { move: "e5", explanation: "Respuesta simétrica en el centro." },
      { move: "Nf3", explanation: "Desarrollo y amenaza sobre e5." },
      { move: "Nc6", explanation: "Defiende el peón central." },
      { move: "Bb5", explanation: "El Ruy López: presiona el caballo defensor." },
      { move: "a6", explanation: "La Morphy: pregunta al alfil qué hará." },
      { move: "Ba4", explanation: "Mantiene la presión sin intercambiar." },
      { move: "Nf6", explanation: "Desarrollo natural atacando e4." },
      { move: "O-O", explanation: "Seguridad del rey antes de acciones centrales." },
      { move: "Be7", explanation: "Negro completa el enroque corto." },
      { move: "Re1", explanation: "La torre apoya e4 y el centro." },
      { move: "b5", explanation: "Gana espacio en el flanco de dama." },
    ],
  },
  {
    id: "scotch-game",
    name: "Apertura Escocesa",
    eco: "C45",
    category: "opening",
    studentColor: "w",
    description: "Juego abierto y táctico desde el inicio.",
    keyIdeas: ["Centro abierto", "Desarrollo rápido", "Táctica temprana"],
    steps: [
      { move: "e4", explanation: "Control del centro." },
      { move: "e5", explanation: "Negro iguala en el centro." },
      { move: "Nf3", explanation: "Desarrollo clásico." },
      { move: "Nc6", explanation: "Defiende e5." },
      { move: "d4", explanation: "La Escocesa: abre el centro inmediatamente." },
      { move: "exd4", explanation: "Negro captura." },
      { move: "Nxd4", explanation: "Recuperas con el caballo bien centrado." },
      { move: "Nf6", explanation: "Ataca e4 y desarrolla." },
      { move: "Nc3", explanation: "Defiende e4 y desarrolla." },
      { move: "Bb4", explanation: "Clavada sobre el caballo c3." },
      { move: "e5", explanation: "Ganas espacio y alejas el caballo negro." },
      { move: "Ne4", explanation: "El caballo busca un puesto activo." },
    ],
  },
  {
    id: "kings-gambit",
    name: "Gambito de Rey",
    eco: "C30",
    category: "opening",
    studentColor: "w",
    description: "Sacrifica un peón por ataque y iniciativa.",
    keyIdeas: ["Ataque al rey", "Iniciativa", "Flanco de rey abierto"],
    steps: [
      { move: "e4", explanation: "Control central." },
      { move: "e5", explanation: "Negro ocupa el centro." },
      { move: "f4", explanation: "El gambito: ofreces un peón por iniciativa." },
      { move: "exf4", explanation: "Negro acepta el gambito." },
      { move: "Nf3", explanation: "Desarrollo con amenaza sobre el peón f4." },
      { move: "g5", explanation: "Defiende f4 agresivamente." },
      { move: "h4", explanation: "Atacas la cadena de peones negros." },
      { move: "g4", explanation: "Negro avanza para mantener el peón." },
      { move: "Ne5", explanation: "Caballo centralizado con gran actividad." },
      { move: "Nf6", explanation: "Desarrollo y contraataque." },
      { move: "Bc4", explanation: "Apuntas a f7, el punto débil." },
      { move: "d5", explanation: "Negro devuelve material para igualar." },
    ],
  },
  {
    id: "london-system",
    name: "Sistema Londres",
    eco: "D02",
    category: "opening",
    studentColor: "w",
    description: "Sistema sólido y universal contra casi todo.",
    keyIdeas: ["Estructura sólida", "Bf4 antes de e3", "Plan fácil de seguir"],
    steps: [
      { move: "d4", explanation: "Control del centro con el peón de dama." },
      { move: "d5", explanation: "Negro ocupa el centro." },
      { move: "Nf3", explanation: "Desarrollo flexible." },
      { move: "Nf6", explanation: "Desarrollo natural de negro." },
      { move: "Bf4", explanation: "El alfil sale antes de bloquearlo con e3." },
      { move: "e6", explanation: "Negro prepara un centro sólido." },
      { move: "e3", explanation: "Sostiene d4 y abre la diagonal del alfil." },
      { move: "Bd6", explanation: "Negro intercambia alfiles activos." },
      { move: "Bxd6", explanation: "Intercambio que simplifica tu plan." },
      { move: "Qxd6", explanation: "La dama recupera el alfil." },
      { move: "c4", explanation: "Ganas espacio en el centro." },
      { move: "O-O", explanation: "Negro enroca para seguridad." },
    ],
  },
  {
    id: "queens-gambit",
    name: "Gambito de Dama",
    eco: "D06",
    category: "opening",
    studentColor: "w",
    description: "Lucha por el centro y el control de c5/d5.",
    keyIdeas: ["Presión en d5", "Desarrollo de piezas", "Ventaja posicional"],
    steps: [
      { move: "d4", explanation: "Control central." },
      { move: "d5", explanation: "Negro iguala en el centro." },
      { move: "c4", explanation: "El gambito de dama: desafías el centro negro." },
      { move: "e6", explanation: "Defensa ortodoxa: sostiene d5." },
      { move: "Nc3", explanation: "Desarrollo y presión sobre d5." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "Bg5", explanation: "Clavada sobre el caballo f6." },
      { move: "Be7", explanation: "Rompe la clavada y prepara el enroque." },
      { move: "e3", explanation: "Centro sólido y desarrollo del alfil." },
      { move: "O-O", explanation: "Seguridad del rey negro." },
      { move: "Nf3", explanation: "Completa el desarrollo menor." },
      { move: "Nbd7", explanation: "Refuerza el centro y desarrolla." },
    ],
  },
  {
    id: "english-opening",
    name: "Apertura Inglesa",
    eco: "A10",
    category: "opening",
    studentColor: "w",
    description: "Control del centro desde el flanco.",
    keyIdeas: ["c4 y fianchetto", "Juego posicional", "Flexibilidad"],
    steps: [
      { move: "c4", explanation: "Control lateral del centro." },
      { move: "e5", explanation: "Negro ocupa el centro con e5." },
      { move: "Nc3", explanation: "Desarrollo y presión sobre d5." },
      { move: "Nf6", explanation: "Desarrollo natural." },
      { move: "g3", explanation: "Prepara el fianchetto del alfil." },
      { move: "Bb4", explanation: "Clavada sobre el caballo c3." },
      { move: "Bg2", explanation: "Alfil en la gran diagonal, muy fuerte." },
      { move: "O-O", explanation: "Negro enroca." },
      { move: "Nf3", explanation: "Completa el desarrollo menor." },
      { move: "Nc6", explanation: "Desarrollo y presión central." },
      { move: "O-O", explanation: "Seguridad del rey blanco." },
      { move: "e4", explanation: "Ganas espacio central decisivo." },
    ],
  },
  {
    id: "catalan-opening",
    name: "Apertura Catalana",
    eco: "E00",
    category: "opening",
    studentColor: "w",
    description: "Fianchetto del alfil con presión sobre el centro.",
    keyIdeas: ["g3 y Bg2", "Control de la diagonal", "Juego posicional"],
    steps: [
      { move: "d4", explanation: "Control central." },
      { move: "Nf6", explanation: "Desarrollo flexible de negro." },
      { move: "c4", explanation: "Amplía el control del centro." },
      { move: "e6", explanation: "Prepara d5." },
      { move: "g3", explanation: "La Catalana: prepara el fianchetto." },
      { move: "d5", explanation: "Negro ocupa el centro." },
      { move: "Bg2", explanation: "Alfil en la diagonal larga presionando d5." },
      { move: "Be7", explanation: "Desarrollo sólido." },
      { move: "Nf3", explanation: "Desarrollo natural." },
      { move: "O-O", explanation: "Enroque negro." },
      { move: "O-O", explanation: "Seguridad del rey blanco." },
      { move: "Nbd7", explanation: "Negro completa el desarrollo." },
    ],
  },
  {
    id: "vienna-game",
    name: "Apertura Vienesa",
    eco: "C25",
    category: "opening",
    studentColor: "w",
    description: "Desarrollo del caballo y presión central temprana.",
    keyIdeas: ["Nc3 rápido", "f4 opcional", "Juego agudo"],
    steps: [
      { move: "e4", explanation: "Control central." },
      { move: "e5", explanation: "Respuesta simétrica." },
      { move: "Nc3", explanation: "La Vienesa: desarrollo del caballo antes de Nf3." },
      { move: "Nf6", explanation: "Ataca e4 y desarrolla." },
      { move: "f4", explanation: "Gambito agresivo por el centro." },
      { move: "d5", explanation: "Negro contraataca en el centro." },
      { move: "fxe5", explanation: "Capturas y abres líneas." },
      { move: "Nxe4", explanation: "El caballo ocupa un puesto central." },
      { move: "Nxe4", explanation: "Recuperas el caballo." },
      { move: "dxe4", explanation: "Negro recaptura." },
      { move: "Qe2", explanation: "Atacas el peón e4 y preparas el enroque." },
      { move: "Nc6", explanation: "Desarrollo de negro." },
    ],
  },
  {
    id: "evans-gambit",
    name: "Gambito Evans",
    eco: "C51",
    category: "opening",
    studentColor: "w",
    description: "Sacrificio de peón por desarrollo rápido y ataque.",
    keyIdeas: ["b4 rompiendo la posición", "Desarrollo superior", "Ataque"],
    steps: [
      { move: "e4", explanation: "Control central." },
      { move: "e5", explanation: "Negro iguala." },
      { move: "Nf3", explanation: "Desarrollo clásico." },
      { move: "Nc6", explanation: "Defiende e5." },
      { move: "Bc4", explanation: "Alfil activo hacia f7." },
      { move: "Bc5", explanation: "Desarrollo simétrico." },
      { move: "b4", explanation: "El Evans: sacrificas un peón por tiempo." },
      { move: "Bxb4", explanation: "Negro acepta." },
      { move: "c3", explanation: "Atacas el alfil y ganas tiempo." },
      { move: "Ba5", explanation: "El alfil se mantiene activo." },
      { move: "d4", explanation: "Centro poderoso con peones conectados." },
      { move: "exd4", explanation: "Negro captura." },
    ],
  },
  {
    id: "four-knights",
    name: "Cuatro Caballos",
    eco: "C47",
    category: "opening",
    studentColor: "w",
    description: "Desarrollo simétrico y sólido.",
    keyIdeas: ["Desarrollo armónico", "Evitar riesgos", "Flexibilidad"],
    steps: [
      { move: "e4", explanation: "Centro." },
      { move: "e5", explanation: "Simetría." },
      { move: "Nf3", explanation: "Desarrollo." },
      { move: "Nc6", explanation: "Defensa de e5." },
      { move: "Nc3", explanation: "Los cuatro caballos: desarrollo sólido." },
      { move: "Nf6", explanation: "Desarrollo simétrico." },
      { move: "Bb5", explanation: "Variante española dentro de cuatro caballos." },
      { move: "Bb4", explanation: "Clavada sobre c3." },
      { move: "O-O", explanation: "Seguridad del rey." },
      { move: "O-O", explanation: "Enroque negro." },
      { move: "d3", explanation: "Centro sólido y flexible." },
      { move: "d6", explanation: "Negro consolida el centro." },
    ],
  },
  {
    id: "trompowsky",
    name: "Ataque Trompowsky",
    eco: "A45",
    category: "opening",
    studentColor: "w",
    description: "Presión inmediata sobre el caballo f6.",
    keyIdeas: ["Bg5 temprano", "Evitar líneas teóricas", "Juego original"],
    steps: [
      { move: "d4", explanation: "Control central." },
      { move: "Nf6", explanation: "Desarrollo flexible." },
      { move: "Bg5", explanation: "El Trompowsky: clavada inmediata." },
      { move: "e6", explanation: "Sólido y prepara d5." },
      { move: "e3", explanation: "Centro sólido." },
      { move: "Be7", explanation: "Desarrollo natural." },
      { move: "Nf3", explanation: "Completa el desarrollo menor." },
      { move: "O-O", explanation: "Enroque negro." },
      { move: "Bd3", explanation: "Desarrollo del alfil de dama." },
      { move: "c5", explanation: "Contraataque en el flanco de dama." },
      { move: "c3", explanation: "Sostiene d4." },
      { move: "Nc6", explanation: "Desarrollo y presión." },
    ],
  },
];